In [1]:
import pandas as pd

In [2]:
df_lights = pd.read_csv("data/LICHTPUNTEN_met_wijk.csv", sep=";") 
df_crimes = pd.read_csv("data/df_crime_average_per_year.csv") 
df_distances = pd.read_csv("data/datapoging2.csv", sep=";")
df_distances.head()

,ID,WijkenEnBuurten,Gemeentenaam_1,SoortRegio_2,Codering_3,IndelingswijzigingWijkenEnBuurten_4,AfstandTotHuisartsenpraktijk_5,Binnen1Km_6,Binnen3Km_7,Binnen5Km_8,...,Binnen5Km_105,Binnen10Km_106,Binnen20Km_107,AfstandTotSauna_108,AfstandTotZonnebank_109,AfstandTotAttractie_110,Binnen10Km_111,Binnen20Km_112,Binnen50Km_113,AfstandTotBrandweerkazerne_114
0,1170,GM0363,Amsterdam,Gemeente,GM0363,3,0.6,3.0,28.3,67.4,...,5.5,11.7,18.2,2.5,2.0,3.2,5.3,13.8,61.4,2.1
1,1171,WK0363AA,Amsterdam,Wijk,WK0363AA,2,0.5,3.8,32.2,96.0,...,10.8,13.0,20.8,1.5,0.8,3.3,6.9,14.0,62.2,1.9
2,1172,BU0363AA01,Amsterdam,Buurt,BU0363AA01,2,0.8,3.8,30.8,87.8,...,11.0,13.0,20.7,1.9,0.4,3.7,6.6,15.0,63.0,1.7
3,1173,BU0363AA02,Amsterdam,Buurt,BU0363AA02,2,0.8,2.3,29.5,87.5,...,10.6,13.0,20.8,1.8,0.7,3.6,6.7,14.9,62.5,2.0
4,1174,BU0363AA03,Amsterdam,Buurt,BU0363AA03,2,0.2,2.0,28.8,92.9,...,10.7,13.0,20.4,1.5,1.3,3.2,7.0,10.7,61.7,2.4

In [3]:
#this was used to explore the differences in wijk names between the two datasets

set1 = set(df_lights['wijknaam'].dropna().str.strip().str.lower())
set2 = set(df_crimes['Wijk'].dropna().str.strip().str.lower()) 

in_both = sorted(set1 & set2)

# Alleen in df1
only_set1 = sorted(set1 - set2)

# Alleen in df2
only_set2 = sorted(set2 - set1)
print(only_set2)
print(only_set1)

[]
['amsterdamse bos', 'bedrijventerreinen', 'bergwijkpark', 'buitengebied', 'diemen centrum', 'diemen zuid', 'groot water', 'halfweg', 'holland park', 'landsmeer', 'muiden', 'patrimonium', 'randwijck', 'spaarndam', 'wijk 00', 'wijk 08 nigtevecht', 'wijk 11 zaandam zuid']

In [4]:
#this was used to explore the differences in wijk names between the two datasets

set1 = set(df_lights['wijkcode'].dropna().str.strip().str.lower())
set2 = set(df_distances['WijkenEnBuurten'].dropna().str.strip().str.lower()) 

in_both = sorted(set1 & set2)

# Alleen in df1
only_set1 = sorted(set1 - set2)

# Alleen in df2
only_set2 = sorted(set2 - set1)
print(in_both)

['wk0363aa', 'wk0363ab', 'wk0363ac', 'wk0363ad', 'wk0363ae', 'wk0363af', 'wk0363ag', 'wk0363ah', 'wk0363aj', 'wk0363ak', 'wk0363ba', 'wk0363bb', 'wk0363ea', 'wk0363eb', 'wk0363ec', 'wk0363ed', 'wk0363ee', 'wk0363ef', 'wk0363eg', 'wk0363eh', 'wk0363ej', 'wk0363ek', 'wk0363el', 'wk0363em', 'wk0363en', 'wk0363ep', 'wk0363eq', 'wk0363er', 'wk0363es', 'wk0363et', 'wk0363eu', 'wk0363ev', 'wk0363fa', 'wk0363fb', 'wk0363fc', 'wk0363fd', 'wk0363fe', 'wk0363ff', 'wk0363fg', 'wk0363fh', 'wk0363fj', 'wk0363fk', 'wk0363fl', 'wk0363fm', 'wk0363fn', 'wk0363fp', 'wk0363fq', 'wk0363ka', 'wk0363kb', 'wk0363kc', 'wk0363kd', 'wk0363ke', 'wk0363kf', 'wk0363kg', 'wk0363kh', 'wk0363kj', 'wk0363kk', 'wk0363kl', 'wk0363km', 'wk0363kn', 'wk0363kp', 'wk0363kq', 'wk0363kr', 'wk0363ma', 'wk0363mb', 'wk0363mc', 'wk0363md', 'wk0363me', 'wk0363mf', 'wk0363mg', 'wk0363mh', 'wk0363mj', 'wk0363mk', 'wk0363ml', 'wk0363mm', 'wk0363mn', 'wk0363mp', 'wk0363mq', 'wk0363na', 'wk0363nb', 'wk0363nc', 'wk0363nd', 'wk0363ne', 'wk0363nf', 'wk0363ng', 'wk0363nh', 'wk0363nj', 'wk0363nk', 'wk0363nl', 'wk0363nm', 'wk0363nn', 'wk0363np', 'wk0363nq', 'wk0363sa', 'wk0363sb', 'wk0363sc', 'wk0363sd', 'wk0363se', 'wk0363ta', 'wk0363tb', 'wk0363tc', 'wk0363td', 'wk0363te', 'wk0363tf', 'wk0363tg', 'wk0363th', 'wk0363tj', 'wk0363tk', 'wk0363tl', 'wk0363tm']

In [5]:
#lantaarn data klaarmaken om te mergen 
df_lights_per_wijk = (
    df_lights
    .groupby(['wijkcode', 'wijknaam'])
    .size()
    .reset_index(name='aantal_lantaarns')
)

df_lights_per_wijk.head()

   wijkcode         wijknaam  aantal_lantaarns
0  WK036201        Randwijck                 1
1  WK036202      Patrimonium                 1
2  WK036214  Amsterdamse Bos               308
3  WK036399      Groot water               118
4  WK0363AA  Haarlemmerbuurt               885

In [6]:
#de wijknaam colomnen schoon maken van beide data sets zodat ik daar op kan mergen 
df_lights_per_wijk['wijknaam_clean'] = (
    df_lights_per_wijk['wijknaam']
    .str.strip()
    .str.lower()
)

df_crimes['wijknaam_clean'] = (
    df_crimes['Wijk']
    .str.strip()
    .str.lower()
)

df_merged = df_lights_per_wijk.merge(
    df_crimes, 
    on='wijknaam_clean',
    how='inner'
)
#merging the lantaarns data with crime data
df_merged = df_merged.drop(columns=['wijknaam_clean', 'Wijk'])  
df_merged.head()

   wijkcode                 wijknaam  aantal_lantaarns  Totaal misdrijven
0  WK0363AA          Haarlemmerbuurt               885               73.0
1  WK0363AB                  Jordaan              1330              150.0
2  WK0363AC      Grachtengordel-West               665               92.0
3  WK0363AD  Burgwallen-Nieuwe Zijde               902              452.0
4  WK0363AE    Burgwallen-Oude Zijde               861              259.0

In [7]:
df_merged['wijkcode_clean']= (
    df_merged['wijkcode'] 
    .str.strip()
    .str.lower()
)

df_distances['wijkcode_clean'] =  (
    df_distances['WijkenEnBuurten']
    .str.strip()
    .str.lower()
)


df_merged_total = df_merged.merge(
    df_distances,  
    on='wijkcode_clean', 
    how='inner'   # alleen wijken die in beide voorkomen
) 

df_merged_total.columns

Index(['wijkcode', 'wijknaam', 'aantal_lantaarns', 'Totaal misdrijven',
       'wijkcode_clean', 'ID', 'WijkenEnBuurten', 'Gemeentenaam_1',
       'SoortRegio_2', 'Codering_3',
       ...
       'Binnen5Km_105', 'Binnen10Km_106', 'Binnen20Km_107',
       'AfstandTotSauna_108', 'AfstandTotZonnebank_109',
       'AfstandTotAttractie_110', 'Binnen10Km_111', 'Binnen20Km_112',
       'Binnen50Km_113', 'AfstandTotBrandweerkazerne_114'],
      dtype='object', length=103)

In [11]:
df_merged_total= df_merged_total.drop(columns=['WijkenEnBuurten', 'Gemeentenaam_1', 'Codering_3', 'Gemeentenaam_1', 'ID', 'SoortRegio_2', 'IndelingswijzigingWijkenEnBuurten_4'])

In [12]:
cols_to_drop = [col for col in df_merged_total.columns if 'Binnen' in col]

df_merged_total = df_merged_total.drop(columns=cols_to_drop) 

df_merged_total

,wijkcode,wijknaam,aantal_lantaarns,Totaal misdrijven,wijkcode_clean,AfstandTotHuisartsenpraktijk_5,AfstandTotHuisartsenpost_9,AfstandTotApotheek_10,AfstandTotZiekenhuis_11,AfstandTotZiekenhuis_15,...,AfstandTotZwembad_93,AfstandTotKunstijsbaan_94,AfstandTotMuseum_95,AfstandTotPodiumkunstenTotaal_99,AfstandTotPoppodium_103,AfstandTotBioscoop_104,AfstandTotSauna_108,AfstandTotZonnebank_109,AfstandTotAttractie_110,AfstandTotBrandweerkazerne_114
0,WK0363AA,Haarlemmerbuurt,885,73.0,wk0363aa,0.5,4.5,0.7,2.0,4.5,...,1.4,6.5,1.2,0.7,2.6,0.9,1.5,0.8,3.3,1.9
1,WK0363AB,Jordaan,1330,150.0,wk0363ab,0.4,3.7,0.5,1.5,3.7,...,0.8,6.8,0.6,0.6,1.5,1.0,1.1,0.8,3.2,0.9
2,WK0363AC,Grachtengordel-West,665,92.0,wk0363ac,0.4,3.9,0.7,1.0,3.9,...,1.2,6.3,0.5,0.5,1.4,1.2,0.6,0.8,3.1,1.3
3,WK0363AD,Burgwallen-Nieuwe Zijde,902,452.0,wk0363ad,0.5,3.7,0.7,0.8,3.7,...,1.6,6.0,0.5,0.8,1.7,1.4,0.5,1.2,2.7,1.7
4,WK0363AE,Burgwallen-Oude Zijde,861,259.0,wk0363ae,0.5,3.2,0.4,1.1,3.2,...,2.1,5.4,0.3,0.5,2.1,1.2,0.5,1.7,2.2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,WK0363TH,K-buurt,1308,29.0,wk0363th,0.5,4.0,0.8,4.0,4.0,...,2.3,6.3,5.8,2.2,7.6,3.7,4.2,4.3,3.3,1.8
106,WK0363TJ,Holendrecht,1905,40.0,wk0363tj,0.9,1.4,0.9,1.4,1.4,...,2.6,8.1,6.6,2.5,9.1,3.5,6.1,6.4,2.9,2.4
107,WK0363TK,Nellestein,1059,18.0,wk0363tk,0.9,3.5,1.5,3.5,3.5,...,2.7,7.1,5.9,2.6,8.4,4.1,5.0,5.3,2.6,0.6
108,WK0363TL,Reigersbos,1743,37.0,wk0363tl,1.0,2.5,1.0,2.5,2.5,...,3.7,8.7,7.5,3.6,9.8,4.6,6.8,7.1,2.6,2.3
109,WK0363TM,Gein,2201,33.0,wk0363tm,0.8,3.5,0.9,3.5,3.5,...,4.1,8.7,8.0,4.0,9.9,5.4,6.8,7.0,1.3,2.3

In [13]:
df_merged_total.to_csv("data/total_table.csv",  index=False)